### ISSUE TITLE
tbl_settings table is not found

### ISSUE THREAD

**Issue by zainamin43** [hammadshahir/php-mysql-ecommerce#20]
Hello, I found the error.
`Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fashiony_ogs.tbl_settings' doesn't exist in C:\xampp\htdocs\PHP-MySQL-ecommerce-website-master\header.php:65 Stack trace: #0 C:\xampp\htdocs\PHP-MySQL-ecommerce-website-master\header.php(65): PDOStatement->execute() #1 C:\xampp\htdocs\PHP-MySQL-ecommerce-website-master\index.php(1): require_once('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\PHP-MySQL-ecommerce-website-master\header.php on line 65`

How can i handle? tbl_settings table is not found in your database. Please reply me

**Comment by zainamin43** [comment]
Hello, I found the error.
`Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fashiony_ogs.tbl_settings' doesn't exist in C:\xampp\htdocs\PHP-MySQL-ecommerce-website-master\header.php:65 Stack trace: #0 C:\xampp\htdocs\PHP-MySQL-ecommerce-website-master\header.php(65): PDOStatement->execute() #1 C:\xampp\htdocs\PHP-MySQL-ecommerce-website-master\index.php(1): require_once('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\PHP-MySQL-ecommerce-website-master\header.php on line 65`

How can i handle? tbl_settings table is not found in your database. Please reply me
